server:
  port: 8080
spring:
  application:
    name: jello-mark-server
  profiles:
    active: dev

jwt:
  secret-key: jello-mark-secret-key-for-development-only-do-not-use-in-production-minimum-256-bits-required
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
